BaseURL = https://backend-lms-hackathon-d1ec76de6bc5.herokuapp.com/lms
InvalidBaseURL = https://backend-lms-hackathon-d1ec76de6bc5.herokuapp.com/
userLoginEmailId = Team02@gmail.com
password = Team02@2026
LoginEndpoint = /login